"""empty message

Revision ID: 908efb4a392e
Revises: 
Create Date: 2019-01-09 11:25:07.493163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908efb4a392e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
